apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: bookstore-portal
  namespace: apps-configuration
spec:
  displayName: Book Store Portal
  description: Developer Portal for Book Store

  # Portal domain
  domains:
    - "portal.$DOMAIN_NAME"

  # Look and feel assets
  banner:
    fetchUrl: https://i.imgur.com/SAC7vCU.jpg
  favicon:
    fetchUrl: https://i.imgur.com/2gUkrIv.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/3TdYUbI.png
  customStyling: {}
  staticPages: []

  # Environment
  publishedEnvironments:
    - name: bookstore-dev
      namespace: apps-configuration

  # This allows users to view APIs without needing to log in
  allApisPublicViewable: false

  # Routing options
  routeOptions:
    cors:
      allowOrigin:
        - 'http://[a-zA-Z0-9]*.$DOMAIN_NAME'
      allowMethods:
        - '*'
      allowHeaders:
        - '*'
