apiVersion: portal.gloo.solo.io/v1beta1
kind: APIProduct
metadata:
  name: bookstore-product
  namespace: apps-configuration
  labels:
    app: bookstore
spec:
  displayInfo: 
    description: Book Store
    title: Book Store

  versions:
    - name: v1
      apis: 
        - apiDoc:
            name: bookstore-schema
            namespace: apps-configuration
      gatewayConfig:
        route:
          ## Demonstrating various ways of referencing the route
          ## -------------------------------------------------
          environmentRoute: envSpecifiedRoute
          ## -------------------------------------------------
          # routeRef:
          #   name: bookstore-route
          #   namespace: apps-configuration
          ## -------------------------------------------------
          # inlineRoute:
          #   backends:
          #     - upstream:
          #         name: bookstore-upstream
          #         namespace: apps-configuration
          ## -------------------------------------------------
      tags:
        stable: {}
