apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: bookstore-dev
  namespace: apps-configuration
spec:
  domains:
    - "api.$DOMAIN_NAME"

  displayInfo:
    description: This environment is meant for developers to deploy and test Book Store APIs.
    displayName: Development

  # Define products, versions and associated usage plans
  apiProducts:
    - namespaces: 
        - '*'
      labels:
        - key: app
          operator: Equals
          values:
            - bookstore
      versions:
        tags:
          - stable
      usagePlans:
        - basic

  parameters:
    # Define all the usage plans
    usagePlans:
      basic:
        displayName: Basic plan with API key auth
        authPolicy:
          apiKey: { }
    # Define parameterized routes
    routes:
      envSpecifiedRoute:
        routeRef:
          name: bookstore-route
          namespace: apps-configuration

  # Override CORS due to content type
  gatewayConfig:
    options:
      cors:
        allowCredentials: true
        allowHeaders:
          - api-key
          - Authorization
          - content-type
        allowOrigin:
          - http://portal.$DOMAIN_NAME
          - https://portal.$DOMAIN_NAME