apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: bookstore-portal
  namespace: apps-configuration
spec:
  displayName: Book Store Portal
  description: Developer Portal for Book Store
  banner:
    fetchUrl: https://i.imgur.com/SAC7vCU.jpg
  favicon:
    fetchUrl: https://i.imgur.com/2gUkrIv.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/3TdYUbI.png
  customStyling: {}
  staticPages: []
  domains:
    - "portal.bookstore.development.internal"
  publishedEnvironments:
    - name: bookstore-dev
      namespace: apps-configuration