apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstore
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-svc
  labels:
    app: bookstore
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: bookstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  labels:
    app: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: bookstore
        version: v1
    spec:
      serviceAccountName: bookstore
      restartPolicy: Always
      containers:
        - name: bookstore
          image: kasunt/gloo-portal-bookstore-demo:1.0.0
          env:
            - name: CONNECTION_STRING
              value: mongodb://bookstore-db-service:27017/bookstore
            - name: PORT
              value: :8080
          ports:
            - name: http
              containerPort: 8080