apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-bookstore-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-bookstore-pv
  labels:
    type: local
spec:
  storageClassName: generic
  claimRef:
    name: mongo-bookstore-pvc
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mongo"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-db-service
  labels:
    app: bookstore-db
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: bookstore-db-pod
---
apiVersion: apps/v1        
kind: Deployment
metadata:
  labels:          
    app: bookstore-db
  name: bookstore-db 
spec:         
  replicas: 1    
  selector: 
    matchLabels:
      app: bookstore-db-pod
  template:
    metadata:
      labels:
        app: bookstore-db-pod
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-bookstore
              mountPath: /var/lib/mongo
      volumes:
        - name: mongo-bookstore
          persistentVolumeClaim:
            claimName: mongo-bookstore-pvc